POST http://localhost:8888/ocr-issue
Content-Type: application/json

{
  "action": "closed",
  "issue": {
    "url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/1",
    "repository_url": "https://api.github.com/repos/i-bcircle/fake-repository",
    "labels_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/1/labels{/name}",
    "comments_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/1/comments",
    "events_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/1/events",
    "html_url": "https://github.com/i-bcircle/fake-repository/issues/1",
    "id": 481537511,
    "node_id": "MDU6SXNzdWU0ODE1Mzc1MTE=",
    "number": 1,
    "title": "Hello world",
    "user": {
      "login": "wk-j",
      "id": 860704,
      "node_id": "MDQ6VXNlcjg2MDcwNA==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/860704?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wk-j",
      "html_url": "https://github.com/wk-j",
      "followers_url": "https://api.github.com/users/wk-j/followers",
      "following_url": "https://api.github.com/users/wk-j/following{/other_user}",
      "gists_url": "https://api.github.com/users/wk-j/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wk-j/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wk-j/subscriptions",
      "organizations_url": "https://api.github.com/users/wk-j/orgs",
      "repos_url": "https://api.github.com/users/wk-j/repos",
      "events_url": "https://api.github.com/users/wk-j/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wk-j/received_events",
      "type": "User",
      "site_admin": false
    },
    "labels": [
      {
        "id": 1503856571,
        "node_id": "MDU6TGFiZWwxNTAzODU2NTcx",
        "url": "https://api.github.com/repos/i-bcircle/fake-repository/labels/area-Meta",
        "name": "area-Meta",
        "color": "ededed",
        "default": false
      },
      {
        "id": 1503763043,
        "node_id": "MDU6TGFiZWwxNTAzNzYzMDQz",
        "url": "https://api.github.com/repos/i-bcircle/fake-repository/labels/feature_request",
        "name": "feature_request",
        "color": "ededed",
        "default": false
      }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [
    ],
    "milestone": null,
    "comments": 1,
    "created_at": "2019-08-16T10:03:15Z",
    "updated_at": "2019-08-16T15:28:07Z",
    "closed_at": "2019-08-16T15:28:07Z",
    "author_association": "COLLABORATOR",
    "body": "![LINE_P201966_104747](https://user-images.githubusercontent.com/19705462/59020178-aa392880-8873-11e9-8b8a-8989cd4bdad3.jpg) By New"
  },
  "repository": {
    "id": 202704718,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDI3MDQ3MTg=",
    "name": "fake-repository",
    "full_name": "i-bcircle/fake-repository",
    "private": false,
    "owner": {
      "login": "i-bcircle",
      "id": 40560555,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjQwNTYwNTU1",
      "avatar_url": "https://avatars1.githubusercontent.com/u/40560555?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/i-bcircle",
      "html_url": "https://github.com/i-bcircle",
      "followers_url": "https://api.github.com/users/i-bcircle/followers",
      "following_url": "https://api.github.com/users/i-bcircle/following{/other_user}",
      "gists_url": "https://api.github.com/users/i-bcircle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/i-bcircle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/i-bcircle/subscriptions",
      "organizations_url": "https://api.github.com/users/i-bcircle/orgs",
      "repos_url": "https://api.github.com/users/i-bcircle/repos",
      "events_url": "https://api.github.com/users/i-bcircle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/i-bcircle/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/i-bcircle/fake-repository",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/i-bcircle/fake-repository",
    "forks_url": "https://api.github.com/repos/i-bcircle/fake-repository/forks",
    "keys_url": "https://api.github.com/repos/i-bcircle/fake-repository/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/i-bcircle/fake-repository/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/i-bcircle/fake-repository/teams",
    "hooks_url": "https://api.github.com/repos/i-bcircle/fake-repository/hooks",
    "issue_events_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/events{/number}",
    "events_url": "https://api.github.com/repos/i-bcircle/fake-repository/events",
    "assignees_url": "https://api.github.com/repos/i-bcircle/fake-repository/assignees{/user}",
    "branches_url": "https://api.github.com/repos/i-bcircle/fake-repository/branches{/branch}",
    "tags_url": "https://api.github.com/repos/i-bcircle/fake-repository/tags",
    "blobs_url": "https://api.github.com/repos/i-bcircle/fake-repository/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/i-bcircle/fake-repository/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/i-bcircle/fake-repository/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/i-bcircle/fake-repository/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/i-bcircle/fake-repository/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/i-bcircle/fake-repository/languages",
    "stargazers_url": "https://api.github.com/repos/i-bcircle/fake-repository/stargazers",
    "contributors_url": "https://api.github.com/repos/i-bcircle/fake-repository/contributors",
    "subscribers_url": "https://api.github.com/repos/i-bcircle/fake-repository/subscribers",
    "subscription_url": "https://api.github.com/repos/i-bcircle/fake-repository/subscription",
    "commits_url": "https://api.github.com/repos/i-bcircle/fake-repository/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/i-bcircle/fake-repository/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/i-bcircle/fake-repository/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/i-bcircle/fake-repository/contents/{+path}",
    "compare_url": "https://api.github.com/repos/i-bcircle/fake-repository/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/i-bcircle/fake-repository/merges",
    "archive_url": "https://api.github.com/repos/i-bcircle/fake-repository/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/i-bcircle/fake-repository/downloads",
    "issues_url": "https://api.github.com/repos/i-bcircle/fake-repository/issues{/number}",
    "pulls_url": "https://api.github.com/repos/i-bcircle/fake-repository/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/i-bcircle/fake-repository/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/i-bcircle/fake-repository/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/i-bcircle/fake-repository/labels{/name}",
    "releases_url": "https://api.github.com/repos/i-bcircle/fake-repository/releases{/id}",
    "deployments_url": "https://api.github.com/repos/i-bcircle/fake-repository/deployments",
    "created_at": "2019-08-16T10:02:15Z",
    "updated_at": "2019-08-16T10:02:15Z",
    "pushed_at": "2019-08-16T10:02:16Z",
    "git_url": "git://github.com/i-bcircle/fake-repository.git",
    "ssh_url": "git@github.com:i-bcircle/fake-repository.git",
    "clone_url": "https://github.com/i-bcircle/fake-repository.git",
    "svn_url": "https://github.com/i-bcircle/fake-repository",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  "organization": {
    "login": "i-bcircle",
    "id": 40560555,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQwNTYwNTU1",
    "url": "https://api.github.com/orgs/i-bcircle",
    "repos_url": "https://api.github.com/orgs/i-bcircle/repos",
    "events_url": "https://api.github.com/orgs/i-bcircle/events",
    "hooks_url": "https://api.github.com/orgs/i-bcircle/hooks",
    "issues_url": "https://api.github.com/orgs/i-bcircle/issues",
    "members_url": "https://api.github.com/orgs/i-bcircle/members{/member}",
    "public_members_url": "https://api.github.com/orgs/i-bcircle/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/40560555?v=4",
    "description": ""
  },
  "sender": {
    "login": "wk-j",
    "id": 860704,
    "node_id": "MDQ6VXNlcjg2MDcwNA==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/860704?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/wk-j",
    "html_url": "https://github.com/wk-j",
    "followers_url": "https://api.github.com/users/wk-j/followers",
    "following_url": "https://api.github.com/users/wk-j/following{/other_user}",
    "gists_url": "https://api.github.com/users/wk-j/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/wk-j/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/wk-j/subscriptions",
    "organizations_url": "https://api.github.com/users/wk-j/orgs",
    "repos_url": "https://api.github.com/users/wk-j/repos",
    "events_url": "https://api.github.com/users/wk-j/events{/privacy}",
    "received_events_url": "https://api.github.com/users/wk-j/received_events",
    "type": "User",
    "site_admin": false
  }
}